mode = "dark"

accent = "#684c59"
selection = "#684c59"
muted = "#6d4745"

background = "#1c1213"
dark_background = "#150d0e"
darker_background = "#0e0909"
lighter_background = "#3a2425"

foreground = "#a87569"
dark_foreground = "#6d4745"
light_foreground = "#c58d7b"
bright_foreground = "#e3a68c"

red = "#c24f57"
yellow = "#f28171"
orange = "#f28171"
green = "#806c61"
cyan = "#6b6566"
blue = "#684c59"
magenta = "#a63650"
brown = "#794038"

bright_red = "#c24f57"
bright_yellow = "#f28171"
bright_green = "#806c61"
bright_cyan = "#6b6566"
bright_blue = "#684c59"
bright_magenta = "#a63650"
